export default {
    ID:0,
    JamID:0,
    JamHour:0,
    JamMinute:0,
    JamSecond:60,
    JamClockState:0,
    BreakHour:0,
    BreakMinute:0,
    BreakSecond:30,
    BreakClockState:0,
    GameHour:0,
    GameMinute:15,
    GameSecond:0,
    GameClockState:0,
    JamCounter:0,
    TeamA:{
        ID:1,
        Index:0,
        Name:"",
        Score:0,
        JamPoints:0,
        Timeotus:3,
        Challenges:3,
        Status:0
    },
    TeamB:{
        ID:2,
        Index:2,
        Name:"",
        Score:0,
        JamPoints:0,
        Timeotus:3,
        Challenges:3,
        Status:0
    },
    PhaseID:0,
    PhaseStatus:0,
    PhaseIndex:0,
    PhaseName:"1st Quarter",
    PhaseHour:0,
    PhaseMinute:0,
    PhaseSecond:0,
    BoardStatus:0,
    BoardStatusText:"",
    ConfirmStatus:false,
    Teams:[
        {ID:1, Name:"Blueberries", Color:"#006699", Logo:"Skate-Blue.png"},
        {ID:2, Name:"Greenbeans", Color:"#009900", Logo:"Skate-Green.png"},
        {ID:3, Name:"Red Skates", Color:"#990000", Logo:"Skate-Red.png"},
        {ID:4, Name:"Brownies", Color:"#996644", Logo:"Skate-Brown.png"},
        {ID:5, Name:"Orange Crushers", Color:"#CC9900", Logo:"Skate-Orange.png"},
        {ID:6, Name:"Pulverizers", Color:"#CC3399", Logo:"Skate-Pink.png"},
        {ID:7, Name:"Terrors", Color:"#009966", Logo:"Skate-Turquoise.png"},
    ],
    Phases:[
        {ID:0,Name:"Setup",Duration:[0,0,0]},
        {ID:1,Name:"Warmups",Duration:[0,40,0]},
        {ID:2,Name:"Intros",Duration:[0,10,0]},
        {ID:3,Name:"1st Quarter",Duration:[0,15,0]},
        {ID:4,Name:"Break",Duration:[0,5,0]},
        {ID:5,Name:"2nd Quarter",Duration:[0,15,0]},
        {ID:6,Name:"Halftime",Duration:[0,20,0]},
        {ID:7,Name:"3rd Quarter",Duration:[0,15,0]},
        {ID:8,Name:"Break",Duration:[0,5,0]},
        {ID:9,Name:"4th Quarter",Duration:[0,15,0]},
        {ID:10,Name:"Final",Duration:[0,0,0]}
    ]
}